Feat: Update link to TuviKeyDerivationLib.
Eppie-io/TuviPgpLib pull request #28
Opened 2023-02-13 09:10 UTC by Gymbotan

Update link to TuviKeyDerivationLib. 
Add PgpKeyBundle (deleted from TuviKeyDerivationLib). 
Update License text (2022 to 2023)

2023-02-13 10:36 UTC, ValeraFinebits approved these changes

2023-02-13 11:40 UTC, al-kau requested changes

2023-02-13 11:40 UTC, al-kau commented on TuviPgpLib/Entities/PgpKeyBundle.cs
> +        public byte[] Data { get; set; }
Will 'Data' be changed outside after creation?

2023-02-14 10:16 UTC, anatolse commented on TuviPgpLib/Entities/PgpKeyBundle.cs
> +        public override bool Equals(object obj)
I suggest implementing IEquiatible<PgpKeyBundle> and implementing Equals via it.
Also, use early return, this should simplify logical expressions and minimize nesting level

2023-02-14 11:40 UTC, anatolse approved these changes

2023-02-14 11:44 UTC, ValeraFinebits approved these changes

2023-02-14 11:45 UTC, merged